AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'spec/**/*.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 40

Metrics/ClassLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 15

Style/ClassVars:
  Enabled: false